FROM node:22-alpine
RUN apk update && apk upgrade --no-cache
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY --chown=root:node tsconfig.json ./
COPY --chown=root:node server/ ./server/
COPY --chown=root:node packages/ ./packages/

RUN mkdir -p /tmp/thirdlayer && chown node:node /tmp/thirdlayer

ENV NODE_ENV=production

USER node

CMD ["npx", "ts-node", "server/services/worker/src/index.ts"]
