FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY --chown=root:node tsconfig.json ./
COPY --chown=root:node server/ ./server/
COPY --chown=root:node packages/ ./packages/

ENV NODE_ENV=production
ENV PORT=3000

EXPOSE 3000

USER node

CMD ["npx", "ts-node", "server/src/index.ts"]
